# Generated by Django 4.2.7 on 2025-11-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('is_maxx', models.BooleanField(default=False)),
                ('is_dluxx', models.BooleanField(default=False)),
                ('is_lux', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('rating', models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance'), ('12A', '12A'), ('15A', '15A'), ('16', '16'), ('18', '18')], max_length=5)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='movie_posters/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='movie_banners/')),
                ('trailer_url', models.URLField(blank=True)),
                ('director', models.CharField(max_length=200)),
                ('cast', models.TextField()),
                ('is_3d', models.BooleanField(default=False)),
                ('is_imax', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_type', models.CharField(choices=[('STANDARD', 'Standard'), ('MAXX', 'OmniplexMAXX'), ('DLUXX', "D'LUXX"), ('LUX', 'LUX'), ('RECLINE', 'Recline')], max_length=20)),
                ('total_seats', models.IntegerField()),
                ('rows', models.IntegerField(default=10)),
                ('seats_per_row', models.IntegerField(default=15)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_3d', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.screen')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('RECLINE', 'Recline'), ('WHEELCHAIR', 'Wheelchair'), ('COMPANION', 'Wheelchair Companion')], default='STANDARD', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('screen', 'row', 'number')},
            },
        ),
    ]
